# Generated by Django 5.0.3 on 2024-03-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_dislikes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Psicologia', 'Psicologia'), ('Auto Ajuda', 'Auto Ajuda'), ('Romance', 'Romance')], default='Psicologia', max_length=50),
        ),
    ]
