# Generated by Django 5.0.3 on 2024-03-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Psicologia', 'Psicologia'), ('Auto Ajuda', 'Auto Ajuda'), ('Romance', 'Romance'), ('Ingles', 'Ingles')], max_length=50),
        ),
    ]
