# Generated by Django 5.0.3 on 2024-03-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
